import type { Metadata } from "next";
import "@/styles/globals.css";
import { siteConfig } from "@/site.config.ts";

import { SiteHeader } from "@/components/ui/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { StickyTitleProvider } from "@/lib/contexts/sticky-title-context";

export const metadata: Metadata = {
  title: siteConfig.name,
  description: "Generated by create next app",
};

export default function CoachingSessionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <SidebarInset className="min-w-0">
          <StickyTitleProvider>
            <SiteHeader />
            <main className="min-w-0">{children}</main>
          </StickyTitleProvider>
        </SidebarInset>
      </div>
    </SidebarProvider>
  );
}
